# Generated by Django 4.0.2 on 2022-05-20 09:43

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mugshot', models.ImageField(upload_to=api.models.name_file)),
                ('face_encoding', models.TextField(editable=False, max_length=900)),
                ('charges', models.CharField(max_length=5000)),
                ('sex', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER'), ('UNKNOWN', 'UNKNOWN')], max_length=7)),
                ('national_id', models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('phone_number', models.IntegerField(unique=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('physical_attributes', models.CharField(max_length=500)),
                ('birth_date', models.DateField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('county', models.CharField(default='null', max_length=200)),
                ('sub_county', models.CharField(default='null', max_length=200)),
                ('constituency', models.CharField(default='null', max_length=200)),
                ('suspect_seen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suspect')),
            ],
        ),
    ]
