# Generated by Django 4.0.2 on 2022-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
